//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lparse.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class LparseLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		NAF=1, NUMBER=2, ID=3, VARIABLE=4, DOT=5, COMMA=6, QUERY_MARK=7, COLON=8, 
		SEMICOLON=9, CONS=10, PLUS=11, MINUS=12, TIMES=13, DIV=14, PAREN_OPEN=15, 
		PAREN_CLOSE=16, SQUARE_OPEN=17, SQUARE_CLOSE=18, CURLY_OPEN=19, CURLY_CLOSE=20, 
		EQUAL=21, UNEQUAL=22, LESS=23, GREATER=24, LESS_OR_EQ=25, GREATER_OR_EQ=26, 
		LINE_COMMENT=27, WS=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"NAF", "NUMBER", "ID", "VARIABLE", "DOT", "COMMA", "QUERY_MARK", "COLON", 
		"SEMICOLON", "CONS", "PLUS", "MINUS", "TIMES", "DIV", "PAREN_OPEN", "PAREN_CLOSE", 
		"SQUARE_OPEN", "SQUARE_CLOSE", "CURLY_OPEN", "CURLY_CLOSE", "EQUAL", "UNEQUAL", 
		"LESS", "GREATER", "LESS_OR_EQ", "GREATER_OR_EQ", "LINE_COMMENT", "WS"
	};


	public LparseLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LparseLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'not'", null, null, null, "'.'", "','", "'?'", "':'", "';'", "':-'", 
		"'+'", "'-'", "'*'", "'/'", "'('", "')'", "'['", "']'", "'{'", "'}'", 
		"'='", null, "'<'", "'>'", "'<='", "'>='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "NAF", "NUMBER", "ID", "VARIABLE", "DOT", "COMMA", "QUERY_MARK", 
		"COLON", "SEMICOLON", "CONS", "PLUS", "MINUS", "TIMES", "DIV", "PAREN_OPEN", 
		"PAREN_CLOSE", "SQUARE_OPEN", "SQUARE_CLOSE", "CURLY_OPEN", "CURLY_CLOSE", 
		"EQUAL", "UNEQUAL", "LESS", "GREATER", "LESS_OR_EQ", "GREATER_OR_EQ", 
		"LINE_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lparse.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LparseLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,28,152,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,1,0,1,
		0,1,0,1,0,1,1,1,1,1,1,5,1,65,8,1,10,1,12,1,68,9,1,3,1,70,8,1,1,2,1,2,5,
		2,74,8,2,10,2,12,2,77,9,2,1,3,1,3,5,3,81,8,3,10,3,12,3,84,9,3,1,4,1,4,
		1,5,1,5,1,6,1,6,1,7,1,7,1,8,1,8,1,9,1,9,1,9,1,10,1,10,1,11,1,11,1,12,1,
		12,1,13,1,13,1,14,1,14,1,15,1,15,1,16,1,16,1,17,1,17,1,18,1,18,1,19,1,
		19,1,20,1,20,1,21,1,21,1,21,1,21,3,21,125,8,21,1,22,1,22,1,23,1,23,1,24,
		1,24,1,24,1,25,1,25,1,25,1,26,1,26,5,26,139,8,26,10,26,12,26,142,9,26,
		1,26,1,26,1,27,4,27,147,8,27,11,27,12,27,148,1,27,1,27,0,0,28,1,1,3,2,
		5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,31,
		16,33,17,35,18,37,19,39,20,41,21,43,22,45,23,47,24,49,25,51,26,53,27,55,
		28,1,0,8,1,0,49,57,1,0,48,57,1,0,97,122,3,0,65,90,95,95,97,122,1,0,65,
		90,4,0,48,57,65,90,95,95,97,122,2,0,10,10,13,13,3,0,9,10,13,13,32,32,158,
		0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,
		0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,
		1,0,0,0,0,25,1,0,0,0,0,27,1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,
		0,0,35,1,0,0,0,0,37,1,0,0,0,0,39,1,0,0,0,0,41,1,0,0,0,0,43,1,0,0,0,0,45,
		1,0,0,0,0,47,1,0,0,0,0,49,1,0,0,0,0,51,1,0,0,0,0,53,1,0,0,0,0,55,1,0,0,
		0,1,57,1,0,0,0,3,69,1,0,0,0,5,71,1,0,0,0,7,78,1,0,0,0,9,85,1,0,0,0,11,
		87,1,0,0,0,13,89,1,0,0,0,15,91,1,0,0,0,17,93,1,0,0,0,19,95,1,0,0,0,21,
		98,1,0,0,0,23,100,1,0,0,0,25,102,1,0,0,0,27,104,1,0,0,0,29,106,1,0,0,0,
		31,108,1,0,0,0,33,110,1,0,0,0,35,112,1,0,0,0,37,114,1,0,0,0,39,116,1,0,
		0,0,41,118,1,0,0,0,43,124,1,0,0,0,45,126,1,0,0,0,47,128,1,0,0,0,49,130,
		1,0,0,0,51,133,1,0,0,0,53,136,1,0,0,0,55,146,1,0,0,0,57,58,5,110,0,0,58,
		59,5,111,0,0,59,60,5,116,0,0,60,2,1,0,0,0,61,70,5,48,0,0,62,66,7,0,0,0,
		63,65,7,1,0,0,64,63,1,0,0,0,65,68,1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,0,
		67,70,1,0,0,0,68,66,1,0,0,0,69,61,1,0,0,0,69,62,1,0,0,0,70,4,1,0,0,0,71,
		75,7,2,0,0,72,74,7,3,0,0,73,72,1,0,0,0,74,77,1,0,0,0,75,73,1,0,0,0,75,
		76,1,0,0,0,76,6,1,0,0,0,77,75,1,0,0,0,78,82,7,4,0,0,79,81,7,5,0,0,80,79,
		1,0,0,0,81,84,1,0,0,0,82,80,1,0,0,0,82,83,1,0,0,0,83,8,1,0,0,0,84,82,1,
		0,0,0,85,86,5,46,0,0,86,10,1,0,0,0,87,88,5,44,0,0,88,12,1,0,0,0,89,90,
		5,63,0,0,90,14,1,0,0,0,91,92,5,58,0,0,92,16,1,0,0,0,93,94,5,59,0,0,94,
		18,1,0,0,0,95,96,5,58,0,0,96,97,5,45,0,0,97,20,1,0,0,0,98,99,5,43,0,0,
		99,22,1,0,0,0,100,101,5,45,0,0,101,24,1,0,0,0,102,103,5,42,0,0,103,26,
		1,0,0,0,104,105,5,47,0,0,105,28,1,0,0,0,106,107,5,40,0,0,107,30,1,0,0,
		0,108,109,5,41,0,0,109,32,1,0,0,0,110,111,5,91,0,0,111,34,1,0,0,0,112,
		113,5,93,0,0,113,36,1,0,0,0,114,115,5,123,0,0,115,38,1,0,0,0,116,117,5,
		125,0,0,117,40,1,0,0,0,118,119,5,61,0,0,119,42,1,0,0,0,120,121,5,60,0,
		0,121,125,5,62,0,0,122,123,5,33,0,0,123,125,5,61,0,0,124,120,1,0,0,0,124,
		122,1,0,0,0,125,44,1,0,0,0,126,127,5,60,0,0,127,46,1,0,0,0,128,129,5,62,
		0,0,129,48,1,0,0,0,130,131,5,60,0,0,131,132,5,61,0,0,132,50,1,0,0,0,133,
		134,5,62,0,0,134,135,5,61,0,0,135,52,1,0,0,0,136,140,5,37,0,0,137,139,
		8,6,0,0,138,137,1,0,0,0,139,142,1,0,0,0,140,138,1,0,0,0,140,141,1,0,0,
		0,141,143,1,0,0,0,142,140,1,0,0,0,143,144,6,26,0,0,144,54,1,0,0,0,145,
		147,7,7,0,0,146,145,1,0,0,0,147,148,1,0,0,0,148,146,1,0,0,0,148,149,1,
		0,0,0,149,150,1,0,0,0,150,151,6,27,0,0,151,56,1,0,0,0,8,0,66,69,75,82,
		124,140,148,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
